config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'  }

  root to: 'pages#home'

  # authenticated :user do
  #   root to:"user#dashboard"
  # end



  resources :users, only: [:show] do
    get 'danger', on: :member
    get 'map', on: :member
    resources :angels, only: [:new, :create, :update, :edit]
  end



  # get 'dashboard/:id' => 'users#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/angel.rb
class Angel < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :angels

  def send_sms
 # Your Auth Token from www.twilio.com/console
    @client = Twilio::REST::Client.new ENV['ACCOUNT_SID'], ENV['AUTH_TOKEN']
    self.angels.each do |angel|
      message = @client.messages.create(
          body: "#{angel.first_name.capitalize} #{angel.last_name.capitalize},

#{self.first_name.capitalize} está em perigo! Acesse o link para ver sua localização ao vivo: www.parserapp.com/users/#{self.id}/map",
          to: "#{angel.phone_number}", # Replace with your phone number
          from: "+12053955462")     # Replace with your Twilio number
      puts message.sid
    end
    puts "angels are comming"
  end

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/angels_controller.rb
class AngelsController < ApplicationController

  def index
    @angels = Angel.all
  end

  def show
    @angel = Angel.find(params[:id])
  end

  def new
    # @user = current_user
    @angel = Angel.new
    # @angel.user_id = current_user.id
  end

  def create
    @angel = Angel.new(angel_params)
    @angel.user_id = current_user.id
    @angel.save!
    redirect_to user_path(current_user)
  end

  def edit
    @angel = Angel.find(params[:id])
  end

  def update
    @angel = Angel.find(params[:id])
    @angel.update(angel_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @angel = Angel.find(params[:id])
    @angel.destroy
    # redirect_to ??
  end

  private

  def angel_params
    params.require(:angel).permit(:first_name, :last_name, :phone_number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
    current_user
  end

  def default_url_options
  { host: ENV["HOST"] || "localhost:3000" }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :address, :phone_number, :car_model, :car_plate, :password, :password_confirmation, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :first_name, :last_name, :address, :phone_number, :car_model, :car_plate])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def test
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    # Require current password if user is trying to change password.
    return super if params["password"]&.present?

    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[danger show map]
  before_action :set_user, only: %i[show danger]
  require 'open-uri'

  def show
  end

  def danger
    @user.send_sms
    head :ok
  end

  def map
    @user = User.find(params[:id])
    url = "https://api.thingspeak.com/channels/630025/feeds.json?api_key=O082B0T51Z0IM9UP&results=2"
    serialized_location = open(url).read
    hash = JSON.parse(serialized_location)
    @latitude = hash["feeds"][1]["field1"]
    @longitude = hash["feeds"][1]["field2"]
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/angels/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="form-edit-box">
        <h2>Editar Angel</h2>

        <%= simple_form_for @angel, url: user_angel_path do |f| %>
          <%= f.error_notification %>

          <%= f.input :first_name,
                        label: "Nome",
                        required: false %>
            <%= f.input :last_name,
                        label: "Sobrenome",
                        required: false %>
            <%= f.input :phone_number,
                        label: "Telefone",
                        required: false %>

      <div class="form-actions">
        <%= f.button :submit, "Atualizar", class: "btn btn-primary" %>
      </div>
        <% end %>
        <%= link_to "Voltar", :back %>
      </div>
    </div>
  </div>
</div>

app/views/angels/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="form-edit-box">

        <h1> Adicionar Angels </h1>

        <%= simple_form_for @angel, url: user_angels_path do |f| %>
          <%= f.input :first_name,
                      label: "Nome",
                      required: true%>
          <%= f.input :last_name,
                      label:"Sobrenome",
                      required: true%>
          <%= f.input :phone_number,
                      label: "Telefone",
                      required: true%>

        <div class="form-actions">
          <%= f.submit "Salvar Angels", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.rawgit.com/oauth-io/oauth-js/c5af4519/dist/oauth.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.12.0/bootstrap-social.min.css">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>

    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/first_page' %>

app/views/pages/test.html.erb
<h1>oi</h1>

app/views/shared/_first_page.html.erb
<div id="home">
  <div class="banner banner-home">
    <video class="teaser-mobile" src ='<%= image_path('teste_easer2.mp4') %>' controls muted loop playinline autoplay style="width: auto; height: 100%; max-width: auto; background: none; overflow: hidden;"></video>
    <video class="teaser" src ='<%= image_path('teste_easer2.mp4') %>' controls muted loop playinline autoplay style="width: 100%; max-width: 100%; height: auto; background: none; overflow: hidden;"></video>
    <%= link_to new_user_session_path do%>
      <% image_tag "logofinal_transparente.png", class: "logo" %>
    <%end%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_map.html.erb
    <div
      id="map"
      style="width: 100%;
      height: 600px;"
    ></div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    <%= render(:partial => 'shared/mapper', :handlers => [:erb], :formats => [:js]) %>
  <% end %>
<% end %>

app/views/shared/_mapper.js.erb
var markers = [];

const initMap = () => {
  var campus = {lat: -23.570991, lng: -46.649886}

  map = new google.maps.Map(document.getElementById('map'), {
    center: campus,
    zoom: 17
  });
  document.getElementById("location").innerHTML = "Google for Startups Campus - Rua Coronel Oscar Porto, 70 - Paraíso, São Paulo - SP, 04003-000"
}

initMap();

const addMarker = (location) => {
  var marker = new google.maps.Marker({
    position: location,
    map: map
  });
  markers.push(marker)
}

const setDangerMarker = () => {

  $.getJSON('https://api.thingspeak.com/channels/630025/feeds.json?api_key=O082B0T51Z0IM9UP&results=2', function(data) {
    var latlng = {
      lat: parseFloat(data.feeds[1].field1),
      lng: parseFloat(data.feeds[1].field2)
    }
    for (var i = 0; i < markers.length; i++ ) {
      markers[i].setMap(null);
    }
    markers.length = 0;
    addMarker(latlng);
    map.setCenter(latlng);
    map.setZoom(17);
    var geocoder = new google.maps.Geocoder;
    geocoder.geocode({'location': latlng}, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
        if (results[1]) {
          document.getElementById("location").innerHTML = results[1].formatted_address;
        }
      }
    });
  });
}


setInterval(setDangerMarker, 10000);

app/views/shared/_navbar.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<div class="navbar-wagon navbar-fixed-bottom footer">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
    <%= image_tag "logoT.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <!-- Links when logged in -->
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
  <div class="navbar-wagon-item">
    <div class="dropdown">
      <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
      <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
    </div>
  </div>
  </div>
</div>

app/views/users/map.html.erb
<meta name="format-detection" content="telephone=no">
<div class="bodymap">
<div class="container">
  <div class="box">
    <div class="row">
      <div class="header">
      <% img = image_path("direcao_diurna.jpg") %>
        <div class="bio-header" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.8)), url('<%= img %>');background-size: cover;background-position: center center;">
        <%= image_tag 'Diego.jpg', class: 'avatar-large' %>
          <h3> <%= @user.first_name %> <%= @user.last_name %></h3>
          <p>Motorista</p>
        </div>
      </div>
    </div>

    <div class="flexbox">
      <div class="flex-item">
        <div class="carinfo">
          <p><strong>Placa</strong></p>
          <p><%= @user.car_plate %></p>
        </div>
      </div>

      <div class="flex-item">
        <div class="carinfo">
          <p><strong>Modelo</strong></p>
          <p><%= @user.car_model %></p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="current-address">


            <span class="blink"> <p><i class="fas fa-exclamation-triangle"></i></p> Atenção: <%= @user.first_name %> está em perigo!</span>
            <div class="lastadress">

           <i class="fas fa-map-marker-alt"> Localização </i>

            <p id="location"></p>
            </div>

            <a href="tel:+55-11-951701220">
              <button type="button" class="btn btn-danger">
                Ligar para Polícia
            </button>
            </a>
          </div>

<a href="tel:"></a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="mapview">
        <%= render 'shared/map' %>
      </div>
    </div>

  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="padding-body container">
  <div class="row">

<!--------- Card1 telefone e email -------------------------------------------------->

    <div class="col-xs-12 col-sm-3">

      <% img_telefone_email = image_path('telefone_email.jpg')%>

      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.4)), url(<%= img_telefone_email %>);">

        <div class="card-description">
          <h2>Informações Gerais</h2>

        </div>
          <a class="card-link" href="#" data-toggle="modal" data-target="#exampleModalCenter" ></a>
<!--------- Modal ------------------------------------------------------------------------->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
         <div class="modal-adpted1">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5> E-mail: <%= current_user.email %></h5>
                <h5> Nome: <%= current_user.first_name %></h5>
                <h5> Sobrenome: <%= current_user.last_name %></h5>
                <h5> Telefone:  <%= current_user.phone_number %></h5>

              </div>
              <div class="modal-footer">

                <%= link_to 'Editar', edit_user_registration_path(info_geral: 'true'), class: 'btn btn-dark' %>
              </div>
            </div>
          </div>
        </div>
      </div>
       </div>
    </div>
<!--------- Card1 ------------------------------------------------------------------------->

<!--------- Card2 Endereço-------------------------------------------------------------->

    <div class="col-xs-12 col-sm-3">

      <% img_endereco1 = image_path('endereço1.jpg') %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.4)), url('<%= img_endereco1 %>');">

        <div class="card-description">
          <h2>Endereço</h2>
        </div>
          <a class="card-link" href="#" data-toggle="modal" data-target="#exampleModalCenter2" ></a>
<!--------- Modal ------------------------------------------------------------------------->
        <div class="modal fade" id="exampleModalCenter2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
         <div class="modal-adpted1">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5> Endereço:  <%= current_user.address %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
              </div>
              <div class="modal-footer">

                <%= link_to 'Editar', edit_user_registration_path(address: 'true'), class: 'btn btn-dark' %>
              </div>
            </div>
          </div>
        </div>
      </div>
       </div>
    </div>
<!--------- Card2 ------------------------------------------------------------------------->

<!--------- Card3  Placa e Modelos --------------------------------------------------------->

    <div class="col-xs-12 col-sm-3">

      <% img_placa1 = image_path('placa1.jpg') %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.4)), url('<%= img_placa1 %>');">


        <div class="card-description">
          <h2>Modelo e Placa</h2>
        </div>
          <a class="card-link" href="#" data-toggle="modal" data-target="#exampleModalCenter3" ></a>
<!--------- Modal ------------------------------------------------------------------------->
        <div class="modal fade" id="exampleModalCenter3" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
         <div class="modal-adpted1">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5> Modelo:  <%= current_user.car_model %></h5>
                <h5> Placa:  <%= current_user.car_plate %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
              </div>
              <div class="modal-footer">

                <%= link_to 'Editar', edit_user_registration_path(car_info: 'true'), class: 'btn btn-dark' %>
              </div>
            </div>
          </div>
        </div>
      </div>
       </div>
    </div>

<!--------- Card4 ANngels ----------------------------------------------------->

    <div class="col-xs-12 col-sm-3">

        <% img_angels = image_path('angels.jpg') %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.4)), url('<%= img_angels %>');">

        <div class="card-description">
          <h2>Angels cadastrados</h2>
        </div>
          <a class="card-link" href="#" data-toggle="modal" data-target="#exampleModalCenter4" ></a>
<!--------- Modal ------------------------------------------------------------------------->
        <div class="modal fade" id="exampleModalCenter4" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
         <div class="modal-adpted2">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h3> Lista de Angels:  </h3>
              </div>
                <% current_user.angels.each_with_index do |angel, i| %>
                  <% break if i > 2 %>
                   <h5> <strong> Angel: </strong>  <%= angel.first_name %> </h5>

                   <h5> <strong> Telefone: </strong>  <%= angel.phone_number %>  <%= link_to 'Editar', edit_user_angel_path(@user, angel), class: 'btn btn-light text-left' %></h5>


                <% end %>
              <div class="modal-footer-angel">

                <%= link_to 'Adicionar', new_user_angel_path(@user), class: 'btn btn-dark' %>
              </div>
            </div>
          </div>
         </div>
       </div>
      </div>
    </div>
  </div>
</div>
</div>
<%= render 'shared/navbar' %>